# Hydra settings
hydra:
  job:
    chdir: false

# Data configuration
data:
  test_file: "data/processed/processed_test_VG6.csv"
  num_operating_modes: 5
  input_feature_cols: [ 'turbine_pressure', 'turbine_rotspeed', 'injector_opening', 'charge', 'coupler_position', 'water_primary_pump_02_opening', 'water_primary_pump_01_opening' ]
  # These are the y_cur columns
  current_value_cols: [
    "air_gap_positive_x_position", "tot_current", "water_circ_flow", "neutral_current",
    "tot_reactivepower", "stat_magn_03_tmp", "stat_coil_ph01_06_tmp", "stat_coil_ph01_04_tmp",
    "air_circ_hot_05_tmp", "air_circ_cold_05_tmp", "water_circ_hot_03_tmp", "plant_tmp",
    "ext_tmp", "tot_activepower"
  ] # These are the y_next columns
  next_value_cols: [
    "air_gap_positive_x_position", "tot_current", "water_circ_flow", "neutral_current",
    "tot_reactivepower", "stat_magn_03_tmp", "stat_coil_ph01_06_tmp", "stat_coil_ph01_04_tmp",
    "air_circ_hot_05_tmp", "air_circ_cold_05_tmp", "water_circ_hot_03_tmp", "plant_tmp",
    "ext_tmp", "tot_activepower"
  ]
  padding_value: 0.0
  load_GT: false
  file_mean_std: "results_VG6/mean_std_VG6_eval.csv"

# Model configuration
model:
  context_length: 60  # 300 / 2 = 150 minutes
  embedding_dim: 32  #
  state_dim: 128     # Increased state dimension for S5 backbone to handle richer data
  num_s5_layers: 4   # Increased number of S5 layers for more complexity
  s5_dropout: 0.1    # Reduced dropout for S5; too high dropout can impact sequence learning negatively
  fc_hidden_dims: [ 128, 64, 32 ]  # Larger and deeper FC network to process richer sequences
  fc_dropout: 0.1   # Reduced FC dropout to preserve signal for complex sequences

# Training configuration
testing:
  batch_size: 64
  model_path: "checkpoints_VG6/causal-ckpt-31900.pth"
  threshold: 4
  window_size: 60
  nb_consecutive_anomalies: 10
  buffer_size: 100
  results_dir: "results_VG6"
  results_file: "results_VG6.csv"
  fig_file: "results_VG6"

# Logging configuration
logging:
  use_wandb: false
  project_name: "alpiq_data_challenge"
  run_name: "train_causal_model_VG6"
