# Hydra settings
hydra:
  job:
    chdir: false

# Data configuration
data:
  train_file: "data/processed/new/processed_train_VG4.csv"
  eval_file: "data/processed/new/processed_eval_VG4.csv"
  num_operating_modes: 5
  input_feature_cols: [ 'injector_opening', 'injector12_pressure', 'pump_rotspeed', 'turbine_rotspeed', 'coupler_position', 'injector34_pressure' ]
  # These are the y_cur columns
  current_value_cols: [
    "ph23_voltage", "ph01_current", "tot_reactivepower", "air_circ_cold_01_tmp",
    "stat_coil_ph01_02_tmp", "plant_tmp", "water_circ_cold_tmp", "water_primary_hot_tmp",
    "water_circ_hot_02_tmp", "water_primary_filter_in_pressure", "canal_level",
    "tot_activepower", "refri_bath_level", "ext_tmp"
  ]  # These are the y_next columns
  next_value_cols: [
    "ph23_voltage", "ph01_current", "tot_reactivepower", "air_circ_cold_01_tmp",
    "stat_coil_ph01_02_tmp", "plant_tmp", "water_circ_cold_tmp", "water_primary_hot_tmp",
    "water_circ_hot_02_tmp", "water_primary_filter_in_pressure", "canal_level",
    "tot_activepower", "refri_bath_level", "ext_tmp"
  ]
  padding_value: 0.0

# Model configuration
model:
  context_length: 240  # 300 / 2 = 150 minutes
  embedding_dim: 64  #
  state_dim: 256     # Increased state dimension for S5 backbone to handle richer data
  num_s5_layers: 6   # Increased number of S5 layers for more complexity
  s5_dropout: 0.1    # Reduced dropout for S5; too high dropout can impact sequence learning negatively
  fc_hidden_dims: [ 256, 128, 64 ]  # Larger and deeper FC network to process richer sequences
  fc_dropout: 0.1   # Reduced FC dropout to preserve signal for complex sequences

# Training configuration
training:
  batch_size: 64
  learning_rate: 0.0005
  num_gradient_steps: 16_000
  checkpoint_folder: "checkpoints_VG4_bigger"

# Logging configuration
logging:
  use_wandb: true
  project_name: "alpiq_data_challenge"
  run_name: "train_causal_model_VG4_bigger"
